version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.8
    platform: linux/amd64
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # 公共入口点配置
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # 环境相关配置
      - "${TRAEFIK_CERT_RESOLVER_COMMAND}"
      - "${TRAEFIK_REDIRECT_MIDDLEWARE_COMMAND}"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-net
    environment:
      - TRAEFIK_ENV=${TRAEFIK_ENV:-production}

  wp:
    image: wordpress:latest
    platform: linux/amd64
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp/html:/var/www/html
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wp.entrypoints=${ENTRYPOINTS}"
      - "traefik.http.routers.wp.middlewares=${MIDDLEWARES}"
      - "traefik.http.services.wp.loadbalancer.server.port=80"
      - "traefik.http.routers.wp.tls=${TLS_ENABLED}"
      - "traefik.http.routers.wp.tls.certresolver=${CERT_RESOLVER}"

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./wp/database:/var/lib/mysql
    networks:
      - traefik-net

#   cdn:
#     build: ./cdn
#     volumes:
#       - ./wp/html:/app/data:rw
#     environment:
#       DATA_PATH: /app/data/
#       DISTRIBUTION_ID: E26EZJCNBKX7UK
#       REGION: us-east-1
#       Bucket: wp-cdn-store
#     entrypoint: ["sh", "-c", "node /app/script/index.js"]
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.cdn.rule=Host(`cdn.your-domain.com`)"  # CDN子域名（按需修改）
#       - "traefik.http.routers.cdn.entrypoints=websecure"
#       - "traefik.http.routers.cdn.tls.certresolver=le"
#       - "traefik.http.services.cdn.loadbalancer.server.port=3000"  # 假设你的CDN服务运行在3000端口
#     networks:
#       - traefik-net

networks:
  traefik-net:
    driver: bridge