services:
    reverse-proxy:
        image: traefik:v2.10
        platform: linux/amd64
        ports:
            - "${HTTP_PORT:-8080}:80"
            - "${HTTPS_PORT:-8443}:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.config/static:/etc/traefik/config/static # 统一配置目录
            - ./traefik.config/dynamic:/etc/traefik/config/dynamic
            - ./letsencrypt:/letsencrypt # 证书存储

        command:
            - "--configfile=/etc/traefik/config/static/${TRAEFIK_ENV_CONFIG:-development}.yml"
            - "--api.insecure=${TRAEFIK_DASHBOARD_ENABLED:-false}"
        environment:
            - "TRAEFIK_ENV_CONFIG=${TRAEFIK_ENV_CONFIG:-development}"
        networks:
            - default

    wp:
        image: wordpress:latest
        platform: linux/amd64
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wp/html:/var/www/html
        networks:
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.wp.loadbalancer.server.port=80"

            - "traefik.http.routers.${ENV}-wp.rule=Host(`${DOMAIN}`) || PathPrefix(`/wp`)"
            - "traefik.http.routers.${ENV}-wp.entrypoints=${ENTRYPOINTS}"
            - "traefik.http.routers.${ENV}-wp.tls=${TLS_ENABLED}"
            - "traefik.http.routers.${ENV}-wp.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
            

    db:
        image: mysql:5.7
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./wp/database:/var/lib/mysql
        networks:
            - default

#   cdn:
#     build: ./cdn
#     volumes:
#       - ./wp/html:/app/data:rw
#     environment:
#       DATA_PATH: /app/data/
#       DISTRIBUTION_ID: E26EZJCNBKX7UK
#       REGION: us-east-1
#       Bucket: wp-cdn-store
#     entrypoint: ["sh", "-c", "node /app/script/index.js"]
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.cdn.rule=Host(`cdn.your-domain.com`)"  # CDN子域名（按需修改）
#       - "traefik.http.routers.cdn.entrypoints=websecure"
#       - "traefik.http.routers.cdn.tls.certresolver=le"
#       - "traefik.http.services.cdn.loadbalancer.server.port=3000"  # 假设你的CDN服务运行在3000端口
#     networks:
#       - default

networks:
    default:
