version: '3.6'

services:
    nginx:
        image: nginx:1.15.7-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/default.conf:/etc/nginx/default.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        networks:
            - default

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - default


    wp:
        image: wordpress:latest
        restart: always
        # ports:
        #   - 80:80
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wp/html:/var/www/html
        networks:
            - default

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./wp/database:/var/lib/mysql
        networks:
            - default

networks:
  default: