version: '3.6'

services:
    nginx:
        image: nginx:1.15.7-alpine
        platform: linux/amd64
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/default.conf:/etc/nginx/default.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        networks:
            - default

    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
        networks:
            - default

    certbot-cron:
        image: certbot/certbot:latest
        container_name: certbot-cron
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./certbot/www:/var/www/certbot:rw  # 必须RW权限
            - ./certbot/conf:/etc/letsencrypt:rw  # 证书存储目录
            - /var/run/docker.sock:/var/run/docker.sock:ro  # 关键点！
        entrypoint: |
            sh -c 'echo "0 3 * * * certbot renew --quiet --post-hook \"docker exec nginx nginx -s reload\"" > /etc/crontabs/root &&
            crond -f'
        restart: unless-stopped  # 推荐配置
        networks:
            - default


    wp:
        image: wordpress:latest
        platform: linux/amd64
        restart: always
        # ports:
        #   - 80:80
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wp/html:/var/www/html
        networks:
            - default

    db:
        image: mysql:5.7
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - ./wp/database:/var/lib/mysql
        networks:
            - default
    
    # cdn:
    #     build: ./cdn
    #     volumes:
    #         - ./wp/html:/app/data:rw
    #     environment:
    #         DATA_PATH: /app/data/
    #         DISTRIBUTION_ID: E26EZJCNBKX7UK
    #         REGION: us-east-1
    #         Bucket: wp-cdn-store
    #     entrypoint: ["sh", "-c", "node /app/script/index.js"]

networks:
  default: