version: '3.6'

services:
    db:
        image: mysql:5.7
        volumes:
            - ~/wordpress/database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: a123456
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: wordpress:latest
        depends_on:
            - db
        ports:
            - 1008:80 # change to 80:80 when the shop is ready to go live
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ~/wordpress/data:/var/www/html/wp-content