global:
  checkNewVersion: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    watch: true
    directory: "/etc/traefik/config/dynamic"

log:
  level: INFO

certificatesResolvers:
  leresolver:
    acme:
      email: jidaqi888@gmail.com    # 替换为真实邮箱
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web